export const CountryStates = [
         "Andhra Pradesh",
         "Arunachal Pradesh",
         "Assam",
         "Bihar",
         "Chhattisgarh",
         "Goa",
         "Gujarat",
         "Haryana",
         "Himachal Pradesh",
         "Jammu & Kashmir",
         "Jharkhand",
         "Karnataka",
         "Kerala",
         "Madhya Pradesh",
         "Maharashtra",
         "Manipur",
         "Meghalaya",
         "Mizoram",
         "Nagaland",
         "Orissa",
         "Punjab",
         "Rajasthan",
         "Sikkim",
         "Tamil Nadu",
         "Telangana",
         "Tripura",
         "Uttar Pradesh",
         "Uttarakhand",
         "West Bengal"
       ];
export const Studies = ["PG", "Bachelor", "+2"];       
